import { useEffect,useState,type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { ensureProfile } from "@/lib/learning";
import { useAuth } from "@/lib/auth";
export default function AuthPage(){const nav=useNavigate();const{user,loading}=useAuth();const[mode,setMode]=useState<"signin"|"signup">("signin");const[name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");useEffect(()=>{if(!loading&&user)nav("/dashboard",{replace:true});},[loading,user,nav]);
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{if(mode==="signup"){if(name.trim().length<2)throw new Error("Enter your full name.");const{data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim()}}});if(error)throw error;if(data.session&&data.user){await ensureProfile(data.user.id,name);nav("/dashboard");}else{setNotice("Account created. Check your email to confirm it, then sign in.");setMode("signin");}}else{const{data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;const n=String(data.user.user_metadata?.full_name??"");if(n)await ensureProfile(data.user.id,n);nav("/dashboard");}}catch(err){setError(err instanceof Error?err.message:"Unable to continue.");}finally{setBusy(false);}}
return <div className="mx-auto grid min-h-[72vh] max-w-6xl gap-10 px-4 py-12 sm:px-6 md:grid-cols-2 md:items-center"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Learner account</p><h1 className="mt-3 text-4xl font-semibold">Learn over time without losing your place.</h1><p className="mt-4 leading-7 text-muted-foreground">Your modules, assessment and certificate stay tied to your account across sessions.</p></div><div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="grid grid-cols-2 rounded-xl bg-muted p-1"><button onClick={()=>setMode("signin")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode==="signin"?"bg-card shadow-sm":""}`}>Sign in</button><button onClick={()=>setMode("signup")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode==="signup"?"bg-card shadow-sm":""}`}>Create account</button></div><form onSubmit={submit} className="mt-6 space-y-4">{mode==="signup"&&<label className="block"><span className="text-sm font-semibold">Full name</span><input required value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-input bg-background px-4 py-3"/></label>}<label className="block"><span className="text-sm font-semibold">Email</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5 w-full rounded-xl border border-input bg-background px-4 py-3"/></label><label className="block"><span className="text-sm font-semibold">Password</span><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5 w-full rounded-xl border border-input bg-background px-4 py-3"/></label>{error&&<p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{notice&&<p className="rounded-xl bg-accent p-3 text-sm text-primary">{notice}</p>}<button disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground">{busy&&<Loader2 className="size-4 animate-spin"/>}{mode==="signup"?"Create learner account":"Sign in and continue"}</button></form></div></div>}
