import { Link } from "react-router-dom";
import { ArrowRight, Award, BookOpen, Clock, LockKeyhole } from "lucide-react";
import { catalog, liveCourses } from "@/lib/courses";
import { useAuth } from "@/lib/auth";

export default function Home(){
 const{user}=useAuth();
 const totalModules=liveCourses.reduce((sum,course)=>sum+course.modules.length,0);
 return <div>
<section className="border-b border-border"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-14 sm:px-6 md:grid-cols-[1.15fr_.85fr] md:items-center md:py-20"><div><p className="inline-flex rounded-full bg-accent px-3 py-1 text-xs font-bold uppercase tracking-[.14em] text-primary">Practical learning for poultry businesses</p><h1 className="mt-5 text-5xl font-semibold leading-[.98] tracking-[-.045em] sm:text-6xl">Choose the pathway that matches the birds you raise.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Broilers, layers and Croiler/dual-purpose flocks need different targets and different business decisions. Learn each system as its own production pathway, with saved progress and a separate certificate.</p><div className="mt-8 flex flex-wrap gap-3"><Link to={user?"/dashboard":"/auth"} className="inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground">{user?"Continue learning":"Start learning"}<ArrowRight className="size-4"/></Link><Link to="/verify" className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-5 py-3 font-semibold"><Award className="size-4 text-gold"/>Verify a certificate</Link></div></div><div className="rounded-[2rem] border border-border bg-card p-7 shadow-xl"><img src="/smartvet-chicken.png" alt="" className="mx-auto h-36 w-36 object-contain"/><div className="mt-4 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl bg-background p-3"><strong className="block text-2xl text-primary">{totalModules}</strong><span className="text-xs text-muted-foreground">modules</span></div><div className="rounded-xl bg-background p-3"><strong className="block text-2xl text-primary">75%</strong><span className="text-xs text-muted-foreground">pass mark</span></div><div className="rounded-xl bg-background p-3"><strong className="block text-2xl text-primary">{liveCourses.length}</strong><span className="text-xs text-muted-foreground">pathways</span></div></div></div></div></section>
<section className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Course catalogue</p><h2 className="mt-2 text-3xl font-semibold">Broiler, Layer and Croiler pathways</h2><p className="mt-3 max-w-3xl leading-7 text-muted-foreground">Each pathway has its own production logic, assessment and certificate. Breed-specific targets should always be checked against the hatchery or breeder guide for the birds on your farm.</p><div className="mt-8 grid gap-5 lg:grid-cols-3">{liveCourses.map(course=><article key={course.id} className="flex flex-col rounded-2xl border border-primary/20 bg-card p-6 shadow-sm"><span className="w-fit rounded-full bg-primary px-2.5 py-1 text-xs font-bold uppercase text-primary-foreground">Live</span><h3 className="mt-4 text-2xl font-semibold">{course.title}</h3><p className="mt-2 flex-1 leading-7 text-muted-foreground">{course.description}</p><div className="mt-5 flex flex-wrap gap-5 text-sm text-muted-foreground"><span className="inline-flex gap-1"><BookOpen className="size-4"/>{course.modules.length} modules</span><span className="inline-flex gap-1"><Clock className="size-4"/>{course.hours} hours</span></div><Link to={user?"/dashboard":"/auth"} className="mt-6 inline-flex items-center gap-2 font-semibold text-primary">Open pathway<ArrowRight className="size-4"/></Link></article>)}</div><div className="mt-5 grid gap-4">{catalog.filter(c=>c.status==="coming-soon").map(c=><article key={c.id} className="rounded-2xl border border-border bg-card p-5 opacity-80"><div className="flex gap-4"><span className="rounded-lg bg-muted p-2"><LockKeyhole className="size-4"/></span><div><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Coming soon</p><h3 className="mt-1 font-semibold">{c.title}</h3><p className="mt-1 text-sm text-muted-foreground">{c.tagline}</p></div></div></article>)}</div></section></div>
}
