CREATE TABLE IF NOT EXISTS module_checks (
  course_id text NOT NULL,
  module_id integer NOT NULL CHECK (module_id > 0),
  question_text text NOT NULL,
  options jsonb NOT NULL CHECK (jsonb_typeof(options) = 'array'),
  correct_index smallint NOT NULL CHECK (correct_index BETWEEN 0 AND 3),
  explanation text NOT NULL,
  published boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (course_id,module_id)
);

INSERT INTO module_checks(course_id,module_id,question_text,options,correct_index,explanation,published)
VALUES
('broiler-foundations',1,'What temperature should be stable at chick level before placement?','["28°C","30°C","33°C","36°C"]'::jsonb,2,'The SmartVet brooding protocol uses about 33°C at chick level before chicks are placed.',true),
('broiler-foundations',2,'What should be ready before the chick box is opened?','["Only the heat source","Drinkers with water and starter feed on trays/paper","The record sheet only","Vaccines only"]'::jsonb,1,'Chicks should find both water and starter feed immediately after placement.',true),
('broiler-foundations',3,'Your eyes sting when you enter the house. What is the best immediate response?','["Ignore it","Improve ventilation, remove wet litter and check drinker leaks","Add more litter next batch only","Reduce feed"]'::jsonb,1,'Eye/nose irritation is a practical ammonia warning. Correct air exchange and the moisture source the same day.',true),
('broiler-foundations',4,'A squishy, floppy crop most strongly suggests:','["Feed and water","Water only — the chick still needs feed","Feed only — the chick needs water","Normal weekly growth"]'::jsonb,1,'A squishy crop points to water intake without enough feed. Improve feed discovery and access, then recheck.',true),
('broiler-foundations',5,'Which statement best describes good biosecurity?','["Spray the house only when birds look sick","Control how people, equipment, animals and contamination move into and around the farm","Use antibiotics routinely","Keep all curtains closed"]'::jsonb,1,'Biosecurity is a movement-and-barrier system. It prevents disease entry and spread before treatment is needed.',true),
('broiler-foundations',6,'Your birds are about 20% below target weight. What should you do?','["Wait another week","Change only the feed brand","Arrange a full SmartVet farm assessment urgently","Sell immediately without investigation"]'::jsonb,2,'A large performance gap needs a whole-farm diagnosis—feed, water, environment, health and records—not a single guessed fix.',true),
('broiler-foundations',7,'When does the current SmartVet routine record dead birds?','["Every morning before 8 am","Weekly","Only after a veterinary visit","Only at sale"]'::jsonb,0,'Daily mortality recording, before 8 am in the current routine, makes sudden changes visible quickly.',true),
('broiler-foundations',8,'More than 1% of the flock dies in one day. What is the correct action?','["Record it and wait a week","Contact SmartVet promptly for possible outbreak assessment","Reduce feed","Increase temperature automatically"]'::jsonb,1,'A sudden mortality spike is an escalation trigger. Record it and seek veterinary assessment promptly.',true),
('broiler-foundations',9,'What FCR does the current course treat as an excellent Cobb500 result around Day 42?','["Under 1.65","1.65–1.75","Above 1.75","Above 2.00"]'::jsonb,0,'The current SmartVet course uses under 1.65 as its excellent Day-42 reference, while farm context still matters.',true),
('layers-foundations',1,'Which measure is most useful for deciding whether a pullet flock is developing correctly before lay?','["Egg price only","Weekly body weight and uniformity","Number of nest boxes only","Age alone"]'::jsonb,1,'Before lay, body weight and flock uniformity are critical evidence that the pullets are developing on schedule.',true),
('layers-foundations',2,'Why is early brooding especially important in layers?','["Because layers are sold for meat at one week","Because early variation can become long-term pullet and laying variation","Because layers do not need feed after six weeks","Because egg size is fixed on day one"]'::jsonb,1,'A poor start creates uneven pullets, and uneven pullets enter lay unevenly and are harder to manage as one flock.',true),
('layers-foundations',3,'What does poor uniformity mean even if the average body weight is on target?','["Every bird is the same size","The average may be hiding many under- and over-weight birds","The flock is ready for photostimulation automatically","Feed intake no longer matters"]'::jsonb,1,'An acceptable average can hide a wide spread of bird sizes, which creates inconsistent maturity and production.',true),
('layers-foundations',4,'If ammonia is strong enough to sting your eyes, what should you do?','["Ignore it until the next flock","Improve ventilation and correct the wet-litter or manure source promptly","Add perfume to the house","Turn off all ventilation"]'::jsonb,1,'Strong ammonia indicates a ventilation and moisture/manure problem that should be corrected promptly.',true),
('layers-foundations',5,'What should guide the decision to stimulate pullets for lay?','["Age only","Body weight, uniformity and the strain lighting guide","Egg price only","The colour of the house"]'::jsonb,1,'Lighting decisions should be coordinated with physiological readiness, especially body weight and uniformity.',true),
('layers-foundations',6,'Which statement about layer calcium is correct?','["Calcium is the only nutrient a laying hen needs","Shell quality depends on calcium plus overall diet balance, intake and health","Calcium is only important during brooding","Adding unlimited limestone fixes every shell problem"]'::jsonb,1,'Eggshell production depends on calcium but also on phosphorus, vitamin D, energy, amino acids, intake, health and environment.',true),
('layers-foundations',7,'How is hen-day production calculated?','["Eggs produced ÷ hens present × 100","Feed used ÷ eggs sold","Hens present ÷ eggs produced × 100","Egg weight ÷ bird age"]'::jsonb,0,'Hen-day production expresses daily eggs as a percentage of hens currently present.',true),
('layers-foundations',8,'Why should cracked and dirty eggs be recorded separately?','["They reveal different causes and different control actions","They are always caused by the same problem","They do not affect profit","Only egg colour matters"]'::jsonb,0,'Different reject categories point to different problems such as shell quality, nest hygiene, floor laying or handling.',true),
('layers-foundations',9,'What is the best way to set a layer vaccination schedule?','["Copy any schedule from social media","Use flock history, hatchery information and local veterinary guidance","Vaccinate only after birds become sick","Use the broiler schedule for every layer flock"]'::jsonb,1,'Disease risk and prior vaccination vary, so the flock needs a locally appropriate, documented programme.',true),
('layers-foundations',10,'Which KPI best connects feed use to the number of eggs a farmer can sell?','["House length","Feed per dozen saleable eggs","Bird feather colour","Calendar week"]'::jsonb,1,'Feed per dozen saleable eggs directly links the major operating input to marketable output.',true),
('croiler-production',1,'What is the first management question for a Croiler or dual-purpose flock?','["What output the flock is meant to produce","What colour the feathers are","How to copy broiler targets","How to avoid all records"]'::jsonb,0,'Dual-purpose birds can serve several markets, so the production objective must be defined before management choices are made.',true),
('croiler-production',2,'Why should Croiler chicks still receive good starter feed?','["Because early development cannot be supplied reliably by scavenging alone","Because they never scavenge later","Because starter feed prevents all disease","Because water is unnecessary"]'::jsonb,0,'Early growth has concentrated nutrient needs; scavenging alone is unreliable for young chicks.',true),
('croiler-production',3,'What is the best description of managed free range?','["Birds roam anywhere with no shelter","Birds forage but still have controlled housing, water, feed and risk management","Birds receive no feed","Predators are accepted as normal losses"]'::jsonb,1,'Free-range management still requires controlled housing, nutrition, water, biosecurity and predator protection.',true),
('croiler-production',4,'What is the safest way to think about scavenging feed?','["It is always nutritionally complete","It can contribute nutrients but should not be assumed to be balanced","It replaces clean water","It makes feed records unnecessary"]'::jsonb,1,'Scavenging varies by place and season, so it should be treated as a contribution rather than a guaranteed balanced ration.',true),
('croiler-production',5,'Why should a farmer avoid comparing Croiler weights directly with broiler targets?','["They have different genetic growth objectives","Weight never matters in Croilers","Broilers and Croilers are identical","Croilers cannot be weighed"]'::jsonb,0,'Dual-purpose birds and specialised broilers are selected for different growth patterns and economics.',true),
('croiler-production',6,'Why can free-range Croilers need strong parasite control?','["They have more contact with soil, intermediate hosts and contaminated environments","Parasites only affect caged birds","Range eliminates all disease","Water is irrelevant to parasites"]'::jsonb,0,'More environmental contact can increase exposure to internal and external parasites.',true),
('croiler-production',7,'Why should supplementation change across seasons?','["Because scavenging resources are not constant through the year","Because birds stop needing nutrients in the rainy season","Because water replaces feed in dry months","Because feed quality never matters"]'::jsonb,0,'The amount and quality of range resources vary with season, so supplementation must respond.',true),
('croiler-production',8,'If Croiler eggs are for table consumption only, is a rooster required for hens to lay?','["Yes, always","No, hens lay without a rooster","Only during the dry season","Only after peak production"]'::jsonb,1,'A rooster is required for fertile eggs, not for ordinary table-egg production.',true),
('croiler-production',9,'Why may home-hatched offspring of commercial dual-purpose hybrids perform differently from their parents?','["Hybrid genetics can segregate in the next generation","Eggs have no genetics","All offspring are always identical","Feed has no influence on performance"]'::jsonb,0,'Many commercial hybrids are crosses, so their offspring can be more variable and may not reproduce the same performance.',true),
('croiler-production',10,'Why is Croiler profitability harder to judge from egg sales alone?','["Because a dual-purpose flock may also create meat and retained-bird value","Because eggs have no value","Because feed is free","Because records are unnecessary"]'::jsonb,0,'Dual-purpose value can come from several outputs, so the whole flock must be considered.',true)
ON CONFLICT(course_id,module_id) DO UPDATE SET
  question_text=EXCLUDED.question_text,
  options=EXCLUDED.options,
  correct_index=EXCLUDED.correct_index,
  explanation=EXCLUDED.explanation,
  published=EXCLUDED.published,
  updated_at=now();

CREATE INDEX IF NOT EXISTS module_checks_course_published_idx
  ON module_checks(course_id,published,module_id);
